# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: eel-ghan <eel-ghan@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/12 13:36:07 by eel-ghan          #+#    #+#              #
#    Updated: 2021/12/13 15:53:19 by eel-ghan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = push_swap

SRCS = push_swap.c ft_putchar_fd.c

OBJS = ${SRCS:.c=.o}

CFLAGS	=	-Wall -Wextra -Werror

CC		=	gcc

AR		=	ar -rc

${NAME} :

all: ${NAME}

clean:

fclean: clean

re: fclean al

.PHONY: all clen fclean re 